//广告key
export  const  ADVERTISEMNET_KEY="AD_KEY"
//baseUrl:
export const BASE_URL="http://10.0.2.2:5000"
//头部高度的存储名称
export const APP_TOP_HEIGHT="TOP_HEIGHT"

//头部底部高度的存储名称
export const APP_BOTTOM_HEIGHT="TOP_HEIGHT"

//存广告的advertise的key
export const ADVERTISE_KEY="ADVERTISE_KEY"
//广告页面窗口的名称
export const ADVERTISE_WINDOW_NAME="ADVERTISE_WINDOW_NAME"
//存储user_id的首选项值
export const USER_ID="USER_ID"
//cookie
export const COOKIE="COOKIE"
//userino
export const  USER_INFO="USER_INFO"
//userino
export const  ADDRESSID="ADDRESSID"
export const  SEARCH_LIST="SEARCH_LIST"